name: hoonete_soojakadu
version: "1.0.0"
profile: hoonete_soojakadu

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target"]

models:
    hoonete_soojakadu:
        staging:
            +materialized: view
            +schema: staging
